spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true


  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: backend-service
    server: http://localhost:${server.port}
    title: Backend service
    version: 1.0.0
